### ISSUE TITLE
Dependency - clojure-contrib 1.1.0

### ISSUE THREAD

**Issue by ryankohl** [jolby/rincanter#1]
I saw the dependencies were updated on the project, so I grabbed the latest off of github.  All went fine until the following popped up:

  An error has occurred while processing the Maven artifact tasks.
   Diagnosis:

  Unable to resolve artifact: Missing:

---

  1) org.clojure:clojure-contrib:jar:1.1.0-master-SNAPSHOT

Any idea why the 1.1.0 snapshot is popping up?

**Comment by jolby** [comment]
Hi,
I'm still wrangling with the native dependencies problem of rincanter.
I think this dependency comes from the jriengine component, which
depends on an old version of lein-clojars, which then depends on an
old clojure-contrib. I'm actually thinking of getting rid of the
packaged native dependency component, and having each user point to
the native shared libraries and jars as installed by R/CRAN.

I'll try to sort this out over the next couple days.

Thanks,
Joel

On Thu, May 26, 2011 at 7:09 AM, ryankohl
reply@reply.github.com
wrote:

> I saw the dependencies were updated on the project, so I grabbed the latest off of github.  All went fine until the following popped up:
> 
>  An error has occurred while processing the Maven artifact tasks.
>   Diagnosis:
> 
>  Unable to resolve artifact: Missing:
>  ----------
>  1) org.clojure:clojure-contrib:jar:1.1.0-master-SNAPSHOT
> 
> Any idea why the 1.1.0 snapshot is popping up?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jolby/rincanter/issues/1

## 

Joel Boehland
p: 360.739.8531
joel.boehland@evocomputing.com
http://evocomputing.com
